Repository OCA/mis-builder, pull requests merged in 2019-10, with the labels that each got.

#236 Improve documentation
  docs/_static/images/analytic.jpg
  docs/_static/images/analytic1.jpg
  docs/_static/images/query_1.png
  docs/_static/images/query_2.png
  docs/_static/images/query_3.png
  docs/usage.rst
Labels: 10.0

#224 [10.0][IMP] committed purchase view - multi currency + analytic tags
  mis_builder_demo/README.rst
  mis_builder_demo/models/mis_committed_purchase.py
  mis_builder_demo/models/mis_committed_purchase.sql
  mis_builder_demo/readme/CONTRIBUTORS.rst
  mis_builder_demo/readme/newsfragments/222.improvement
  mis_builder_demo/views/mis_committed_purchase.xml
Labels: 10.0, enhancement, needs review

#228 [10.0][IMP] Add analytic tags as filter for mis_builder
  mis_builder/models/mis_report_instance.py
  mis_builder/static/src/js/mis_report_widget.js
  mis_builder/static/src/xml/mis_report_widget.xml
  mis_builder/tests/test_analytic_filters.py
  mis_builder/views/mis_report_instance.xml
Labels: 10.0, approved, enhancement, needs review

#241 [FIX] analytic tags in budget item overlap detection
  mis_builder_budget/models/mis_budget_item.py
  mis_builder_budget/readme/newsfragments/241.bugfix
Labels: 10.0, bug

#242 [10.0][IMP] mis_builder: Show company of account detail in multicompany
  mis_builder/models/kpimatrix.py
  mis_builder/models/mis_report.py
  mis_builder/models/mis_report_instance.py
  mis_builder/tests/test_mis_report_instance.py
Labels: approved

#223 [FIX] Percentage point (pp) values do not export correctly to Excel
  mis_builder/README.rst
  mis_builder/models/kpimatrix.py
  mis_builder/models/mis_report_style.py
  mis_builder/readme/CONTRIBUTORS.rst
  mis_builder/readme/newsfragments/220.bugfix
  mis_builder/report/mis_report_instance_xlsx.py
  mis_builder/tests/test_render.py
Labels: 10.0, bug, needs review

#182 [FIX] propagate context to xlsx report
  mis_builder/models/mis_report_instance.py
  mis_builder/readme/newsfragments/178.bugfix
Labels: 11.0, bug

#245 [11.0] analytic filters in widget, take 5
  mis_builder/static/src/css/custom.css
  mis_builder/static/src/js/mis_report_widget.js
  mis_builder/static/src/xml/mis_report_widget.xml
Labels: 11.0, migration
