Repository OCA/mis-builder, pull requests merged in 2020-11, with the labels that each got.

#335 [13.0][PORT] 304 from 12.0
  mis_builder/models/mis_report.py
  mis_builder/models/mis_report_instance.py
  mis_builder/readme/newsfragments/304.feature
  mis_builder/tests/test_mis_report_instance.py
Labels: bot is merging ⏳, needs review

#304 Fix drilldown action name
  mis_builder/models/mis_report.py
  mis_builder/models/mis_report_instance.py
  mis_builder/readme/newsfragments/304.feature
  mis_builder/tests/test_mis_report_instance.py
Labels: 12.0, approved, bot is merging ⏳, needs review, ready to merge

#334 [11.0][PORT] 304 from 12.0
  mis_builder/models/mis_report.py
  mis_builder/models/mis_report_instance.py
  mis_builder/readme/newsfragments/304.feature
  mis_builder/tests/test_mis_report_instance.py
Labels: bot is merging ⏳

#333 [10.0][PORT] 304 from 12.0
  mis_builder/models/mis_report.py
  mis_builder/models/mis_report_instance.py
  mis_builder/readme/newsfragments/304.feature
  mis_builder/tests/test_mis_report_instance.py
Labels: bot is merging ⏳
