Repository OCA/mis-builder, pull requests merged in 2020-08, with the labels that each got.

#300 [FIX] mis_builder: Comparison percentages export format in XLSX
  mis_builder/readme/newsfragments/300.bugfix
  mis_builder/report/mis_report_instance_xlsx.py
Labels: 10.0, approved, bot is merging ⏳, bug, ready to merge

#314 [13.0][PORT] 300 from 10.0
  mis_builder/readme/newsfragments/300.bugfix
  mis_builder/report/mis_report_instance_xlsx.py
Labels: 13.0, bot is merging ⏳

#311 fix read_group fields arguments
  mis_builder/models/prorata_read_group_mixin.py
  mis_builder/readme/newsfragments/296.bugfix
Labels: 10.0, bot is merging ⏳

#312 [11.0][PORT] 300 from 10.0
  mis_builder/readme/newsfragments/300.bugfix
  mis_builder/report/mis_report_instance_xlsx.py
Labels: 11.0, bot is merging ⏳

#313 [12.0][PORT] 300 from 10.0
  mis_builder/readme/newsfragments/300.bugfix
  mis_builder/report/mis_report_instance_xlsx.py
Labels: 12.0, bot is merging ⏳

#317 [13.0][PORT] 315 from 11.0
  mis_builder/models/prorata_read_group_mixin.py
  mis_builder/readme/newsfragments/296.misc
Labels: 13.0, bot is merging ⏳

#315 [11.0][PORT] 311 from 10.0
  mis_builder/models/prorata_read_group_mixin.py
  mis_builder/readme/newsfragments/296.misc
Labels: 11.0, bot is merging ⏳

#316 [12.0][PORT] 315 from 11.0
  mis_builder/models/prorata_read_group_mixin.py
  mis_builder/readme/newsfragments/296.misc
Labels: 12.0, bot is merging ⏳
