Repository OCA/mis-builder, pull requests merged in 2020-04, with the labels that each got.

#284 [10.0][PORT] 277 from 13.0
  mis_builder/models/prorata_read_group_mixin.py
  mis_builder/readme/newsfragments/276.bugfix
Labels: bot is merging ⏳

#282 [12.0][PORT] 277 from 13.0
  mis_builder/models/prorata_read_group_mixin.py
  mis_builder/readme/newsfragments/276.bugfix
Labels: 12.0, bot is merging ⏳, bug

#283 [11.0][PORT] 277 from 13.0
  mis_builder/models/prorata_read_group_mixin.py
  mis_builder/readme/newsfragments/276.bugfix
Labels: 11.0, bot is merging ⏳, bug

#291 Fix regression introduced in Odoo e23e8a4
  mis_builder/tests/test_aep.py
Labels: 13.0, bot is merging ⏳

#277 Fix 'module' object is not iterable in ProRataReadGroupMixin
  mis_builder/models/prorata_read_group_mixin.py
  mis_builder/readme/newsfragments/276.bugfix
Labels: 13.0, bot is merging ⏳, bug

#281 [FIX] Non-existing security group linked to "Settings" button in MIS Widget
  mis_builder/readme/newsfragments/281.bugfix
  mis_builder/static/src/js/mis_report_widget.js
Labels: 11.0, bot is merging ⏳, bug

#285 [12.0][PORT] #281 from 11.0
  mis_builder/readme/newsfragments/281.bugfix
  mis_builder/static/src/js/mis_report_widget.js
Labels: 12.0, bot is merging ⏳, bug

#286 [13.0][PORT] #281 from 11.0
  mis_builder/readme/newsfragments/281.bugfix
  mis_builder/static/src/js/mis_report_widget.js
Labels: 13.0, bot is merging ⏳, bug

#287 [10.0][PORT] 274 from 12.0
  mis_builder_demo/models/mis_committed_purchase.sql
  mis_builder_demo/readme/newsfragments/274.bugfix
Labels: 10.0, bot is merging ⏳, bug

#274 [12.0] fix currency rate in uninvoiced purchases
  mis_builder_demo/models/mis_committed_purchase.sql
  mis_builder_demo/readme/newsfragments/274.bugfix
Labels: 12.0, bot is merging ⏳, bug

#288 [11.0][PORT] 274 from 12.0
  mis_builder_demo/models/mis_committed_purchase.sql
  mis_builder_demo/readme/newsfragments/274.bugfix
Labels: 11.0, bot is merging ⏳, bug

#289 [13.0][PORT] 274 from 12.0
  mis_builder_demo/models/mis_committed_purchase.sql
  mis_builder_demo/readme/newsfragments/274.bugfix
Labels: 13.0, bot is merging ⏳, bug

#292 Restore _intersect_days (as a model method)
  mis_builder/models/mis_kpi_data.py
  mis_builder/models/prorata_read_group_mixin.py
  mis_builder/readme/newsfragments/280.misc
Labels: 10.0, bot is merging ⏳

#295 [13.0][PORT] 292 from 10.0
  mis_builder/models/mis_kpi_data.py
  mis_builder/models/prorata_read_group_mixin.py
  mis_builder/readme/newsfragments/280.misc
Labels: 13.0, bot is merging ⏳

#293 [11.0][PORT] 292 from 10.0
  mis_builder/models/mis_kpi_data.py
  mis_builder/models/prorata_read_group_mixin.py
  mis_builder/readme/newsfragments/280.misc
Labels: 11.0, bot is merging ⏳

#294 [12.0][PORT] 292 from 10.0
  mis_builder/models/mis_kpi_data.py
  mis_builder/models/prorata_read_group_mixin.py
  mis_builder/readme/newsfragments/280.misc
Labels: 12.0, bot is merging ⏳
