Repository OCA/mis-builder, pull requests merged in 2021-06, with the labels that each got.

#365 [14.0] Use GitHub actions instread of travis
  .copier-answers.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .travis.yml
Labels: 14.0, bot is merging ⏳

#361 [14.0][FIX] mis_builder: compute comparison domain correctly
  mis_builder/models/mis_report_instance.py
  mis_builder/readme/newsfragments/361.bugfix
  mis_builder/views/mis_report_instance.xml
Labels: 14.0, approved, bot is merging ⏳, bugfix

#367 [12.0][DEL] Old migration scripts
  mis_builder/migrations/8.0.2.0.0/post-migration.py
  mis_builder/migrations/8.0.2.0.0/pre-migration.py
Labels: approved, bot is merging ⏳, ready to merge
