Repository OCA/mis-builder, pull requests merged in 2021-12, with the labels that each got.

#395 [13.0][FIX] mis_builder: Remove old migration scripts
  mis_builder/migrations/8.0.2.0.0/post-migration.py
  mis_builder/migrations/8.0.2.0.0/pre-migration.py
Labels: bot is merging ⏳

#390 [14.0][FIX]mis_builder: do not pass bare module to safe_eval
  mis_builder/models/mis_report.py
Labels: bot is merging ⏳, bugfix

#364 [12.0][FIX] balu[] and budgets by account fails
  mis_builder/models/aep.py
  mis_builder/readme/newsfragments/364.bugfix
Labels: 12.0, bot is merging ⏳, bugfix
