Repository OCA/mis-builder, pull requests merged in 2021-10, with the labels that each got.

#382 [13.0] Add labels to mis budget by account items
  mis_builder_budget/models/mis_budget_by_account_item.py
  mis_builder_budget/readme/newsfragments/382.feature
  mis_builder_budget/views/mis_budget_by_account_item.xml
Labels: needs review, 13.0

#383 [13.0] Make balance field writeable on mis budget by account items
  mis_builder_budget/models/mis_budget_by_account_item.py
  mis_builder_budget/readme/newsfragments/383.feature
  mis_builder_budget/tests/test_mis_budget_by_account.py
  mis_builder_budget/views/mis_budget_by_account_item.xml
Labels: needs review, 13.0

#384 [13.0] allow overlapping Budget by Account items
  mis_builder_budget/models/mis_budget_by_account.py
  mis_builder_budget/models/mis_budget_by_account_item.py
  mis_builder_budget/readme/newsfragments/384.feature
  mis_builder_budget/views/mis_budget_by_account.xml
Labels: 13.0

#377 [13.0] ignore moves in 'cancel' state
  mis_builder/models/aep.py
  mis_builder/models/expression_evaluator.py
  mis_builder/models/mis_report.py
  mis_builder/models/mis_report_instance.py
  mis_builder/tests/__init__.py
  mis_builder/tests/test_aep.py
  mis_builder/tests/test_multi_company_aep.py
  mis_builder/tests/test_target_move.py
  mis_builder_budget/models/mis_report_instance.py
  mis_builder_budget/models/mis_report_instance_period.py
Labels: needs review, 13.0

#387 [13.0-4.0-staging][PORT] 332 from 12.0
  mis_builder/models/mis_report.py
  mis_builder/models/mis_report_instance.py
  mis_builder/models/mis_report_style.py
  mis_builder/readme/CONTRIBUTORS.rst
  mis_builder/wizard/mis_builder_dashboard.py
Labels: 13.0

#332 [IMP] mis_builder: remove field size limit
  mis_builder/models/mis_report.py
  mis_builder/models/mis_report_instance.py
  mis_builder/models/mis_report_style.py
  mis_builder/readme/CONTRIBUTORS.rst
  mis_builder/wizard/mis_builder_dashboard.py
Labels: enhancement, 12.0, bot is merging ⏳

#385 [11.0][PORT] 332 from 12.0
  mis_builder/models/mis_report.py
  mis_builder/models/mis_report_instance.py
  mis_builder/models/mis_report_style.py
  mis_builder/readme/CONTRIBUTORS.rst
  mis_builder/wizard/mis_builder_dashboard.py
Labels: 11.0, bot is merging ⏳

#386 [10.0][PORT] 332 from 12.0
  mis_builder/models/mis_report.py
  mis_builder/models/mis_report_instance.py
  mis_builder/models/mis_report_style.py
  mis_builder/readme/CONTRIBUTORS.rst
  mis_builder/wizard/mis_builder_dashboard.py
Labels: 10.0, bot is merging ⏳
