Repository OCA/mis-builder, pull requests merged in 2022-01, with the labels that each got.

#381 [13.0] MIS Builder 4.0 staging
  mis_builder/i18n/mis_builder.pot
  mis_builder/models/aep.py
  mis_builder/models/expression_evaluator.py
  mis_builder/models/mis_report.py
  mis_builder/models/mis_report_instance.py
  mis_builder/models/mis_report_style.py
  mis_builder/readme/CONTRIBUTORS.rst
  mis_builder/readme/newsfragments/327.bugfix
  mis_builder/readme/newsfragments/332.feature
  mis_builder/readme/newsfragments/375.bugfix
  mis_builder/readme/newsfragments/377.bugfix
  mis_builder/security/mis_builder_security.xml
  mis_builder/tests/__init__.py
  mis_builder/tests/test_aep.py
  mis_builder/tests/test_mis_report_instance.py
  mis_builder/tests/test_multi_company_aep.py
  mis_builder/tests/test_target_move.py
  mis_builder/views/mis_report_instance.xml
  mis_builder/wizard/mis_builder_dashboard.py
  mis_builder_budget/i18n/mis_builder_budget.pot
  mis_builder_budget/models/mis_budget_by_account.py
  mis_builder_budget/models/mis_budget_by_account_item.py
  mis_builder_budget/models/mis_report_instance.py
  mis_builder_budget/models/mis_report_instance_period.py
  mis_builder_budget/readme/newsfragments/382.feature
  mis_builder_budget/readme/newsfragments/383.feature
  mis_builder_budget/readme/newsfragments/384.feature
  mis_builder_budget/tests/test_mis_budget_by_account.py
  mis_builder_budget/views/mis_budget_by_account.xml
  mis_builder_budget/views/mis_budget_by_account_item.xml
Labels: needs review, approved, ready to merge, 13.0, bot is merging ⏳

#400 [14.0] port mis-builder 4.0 from 13.0
  .github/workflows/tests.yml
  mis_builder/i18n/mis_builder.pot
  mis_builder/models/aep.py
  mis_builder/models/expression_evaluator.py
  mis_builder/models/mis_report.py
  mis_builder/models/mis_report_instance.py
  mis_builder/models/mis_report_style.py
  mis_builder/readme/CONTRIBUTORS.rst
  mis_builder/readme/HISTORY.rst
  mis_builder/readme/newsfragments/327.bugfix
  mis_builder/readme/newsfragments/332.feature
  mis_builder/readme/newsfragments/375.bugfix
  mis_builder/readme/newsfragments/377.bugfix
  mis_builder/security/mis_builder_security.xml
  mis_builder/tests/__init__.py
  mis_builder/tests/test_aep.py
  mis_builder/tests/test_mis_report_instance.py
  mis_builder/tests/test_multi_company_aep.py
  mis_builder/tests/test_target_move.py
  mis_builder/views/mis_report_instance.xml
  mis_builder/wizard/mis_builder_dashboard.py
  mis_builder_budget/i18n/mis_builder_budget.pot
  mis_builder_budget/models/mis_budget_by_account.py
  mis_builder_budget/models/mis_budget_by_account_item.py
  mis_builder_budget/models/mis_report_instance.py
  mis_builder_budget/models/mis_report_instance_period.py
  mis_builder_budget/readme/newsfragments/382.feature
  mis_builder_budget/readme/newsfragments/383.feature
  mis_builder_budget/readme/newsfragments/384.feature
  mis_builder_budget/tests/test_mis_budget_by_account.py
  mis_builder_budget/views/mis_budget_by_account.xml
  mis_builder_budget/views/mis_budget_by_account_item.xml
Labels: needs review, approved, bot is merging ⏳, 14.0

#405 [MIG] mis-builder: Migration to 15.0
  .pre-commit-config.yaml
  mis_builder/__manifest__.py
  mis_builder/models/aep.py
  mis_builder/models/expression_evaluator.py
  mis_builder/models/kpimatrix.py
  mis_builder/models/mis_kpi_data.py
  mis_builder/models/mis_report.py
  mis_builder/models/mis_report_instance.py
  mis_builder/models/mis_report_style.py
  mis_builder/models/mis_report_subreport.py
  mis_builder/report/mis_report_instance_qweb.py
  mis_builder/report/mis_report_instance_qweb.xml
  mis_builder/tests/test_analytic_filters.py
  mis_builder/tests/test_kpi_data.py
  mis_builder/tests/test_multi_company_aep.py
  mis_builder/views/mis_report.xml
  mis_builder/views/mis_report_instance.xml
  mis_builder/views/mis_report_style.xml
  mis_builder/wizard/mis_builder_dashboard.py
  setup/mis_builder/odoo/addons/mis_builder
  setup/mis_builder/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#407 Set mis_builder version to 4.0
  mis_builder/__manifest__.py
Labels: bot is merging ⏳

#409 [IMP] mis_builder_budget: remove redundant super className in Python3
  mis_builder_budget/models/mis_budget_abstract.py
  mis_builder_budget/models/mis_budget_by_account_item.py
  mis_builder_budget/models/mis_budget_item.py
  mis_builder_budget/models/mis_report_instance.py
  mis_builder_budget/models/mis_report_instance_period.py
  mis_builder_budget/models/mis_report_kpi_expression.py
  mis_builder_budget/tests/test_mis_budget.py
  mis_builder_budget/tests/test_mis_budget_by_account.py
Labels: bot is merging ⏳
