Repository OCA/mis-builder, pull requests merged in 2022-03, with the labels that each got.

#421 [14.0][FIX] mis_builder: Be tolerant in tests with several installed companies
  mis_builder/tests/test_mis_report_instance.py
Labels: bot is merging ⏳

#422 [15.0][PORT] 421 from 14.0
  mis_builder/tests/test_mis_report_instance.py
Labels: approved, bot is merging ⏳, 15.0

#423 [13.0][PORT] 421 from 14.0
  mis_builder/tests/test_mis_report_instance.py
Labels: approved, 13.0, bot is merging ⏳
