Repository OCA/mis-builder, pull requests merged in 2023-11, with the labels that each got.

#581 [FIX] string format
  mis_builder/models/kpimatrix.py
Labels: bot is merging ⏳, 16.0

#580 [15.0] update dotfiles
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  mis_builder/models/kpimatrix.py
  mis_builder/models/mis_report.py
  mis_builder/report/mis_report_instance_xlsx.py
Labels: bot is merging ⏳, 15.0

#586 [FIX] mis_builder: date_range test
  mis_builder/tests/test_period_dates.py
Labels: bot is merging ⏳, 16.0

#577 [16.0] update dotfiles, use ruff
  .copier-answers.yml
  .flake8
  .gitignore
  .isort.cfg
  .pre-commit-config.yaml
  .ruff.toml
  mis_builder/models/accounting_none.py
  mis_builder/models/aep.py
  mis_builder/models/data_error.py
  mis_builder/models/expression_evaluator.py
  mis_builder/models/kpimatrix.py
  mis_builder/models/mis_report.py
  mis_builder/models/mis_report_instance.py
  mis_builder/models/mis_report_style.py
  mis_builder/models/prorata_read_group_mixin.py
  mis_builder/models/simple_array.py
  mis_builder/report/mis_report_instance_xlsx.py
  mis_builder/tests/fake_models.py
  mis_builder/tests/test_aep.py
  mis_builder/tests/test_mis_report_instance.py
  mis_builder_budget/models/mis_budget.py
  mis_builder_budget/models/mis_budget_abstract.py
  mis_builder_budget/models/mis_budget_by_account.py
  mis_builder_budget/models/mis_budget_by_account_item.py
  mis_builder_budget/models/mis_budget_item.py
  mis_builder_budget/models/mis_budget_item_abstract.py
  mis_builder_budget/models/mis_report_instance.py
  mis_builder_budget/models/mis_report_instance_period.py
  mis_builder_budget/models/mis_report_kpi.py
  mis_builder_budget/models/mis_report_kpi_expression.py
  mis_builder_budget/tests/test_mis_budget_by_account.py
  mis_builder_demo/models/mis_committed_purchase.py
Labels: bot is merging ⏳

#588 [14.0][IMP] add: css sticky table header added for mis-builder-widget
  mis_builder/static/src/css/custom.css
Labels: approved
