Repository OCA/mis-builder, pull requests merged in 2024-10, with the labels that each got.

#632 [16.0][FIX] mis_builder: Add analytic_domain to report instance only if it is set
  mis_builder/migrations/16.0.1.0.1/post-migration.py
  mis_builder/migrations/8.0.2.0.0/post-migration.py
  mis_builder/migrations/8.0.2.0.0/pre-migration.py
  mis_builder/models/mis_report_instance.py
Labels: approved, ready to merge, 16.0, Needs PORT

#634 [IMP] mis_builder_budget: allow Analytic Accounts on account budget
  mis_builder_budget/models/mis_budget_by_account_item.py
  mis_builder_budget/views/mis_budget_by_account_item.xml
Labels: bot is merging ⏳, 17.0, Needs PORT

#589 [16.0][IMP] allow multi-company MIS budgets by account
  mis_builder_budget/models/mis_budget_by_account.py
  mis_builder_budget/models/mis_budget_by_account_item.py
Labels: no stale, 16.0, Needs PORT

#636 [17.0][FIX] mis_builder: Add analytic_domain to report instance only if it is set
  mis_builder/models/mis_report_instance.py
Labels: approved, bot is merging ⏳

#637 [17.0] port #589 from 16.0
  mis_builder_budget/models/mis_budget_by_account.py
  mis_builder_budget/models/mis_budget_by_account_item.py
Labels: needs review, bot is merging ⏳, 17.0

#638 [16.0][PORT] 634 from 17.0
  mis_builder_budget/models/mis_budget_by_account_item.py
  mis_builder_budget/views/mis_budget_by_account_item.xml
Labels: bot is merging ⏳, 16.0
