Repository OCA/mis-builder, pull requests merged in 2025-09, with the labels that each got.

#722 [IMP] mis_builder: use new 'path' feature to improve urls.
  mis_builder/views/mis_report.xml
  mis_builder/views/mis_report_instance.xml
  mis_builder/views/mis_report_style.xml
  mis_builder_budget/views/mis_budget.xml
  mis_builder_budget/views/mis_budget_by_account.xml
  mis_builder_budget/views/mis_budget_by_account_item.xml
  mis_builder_budget/views/mis_budget_item.xml
Labels: bot is merging ⏳, 18.0

#719 [IMP] mis_builder: display fields allways in the same place.
  mis_builder/views/mis_report_style.xml
Labels: approved, bot is merging ⏳, 18.0

#725 [18.0][MIG/IMP] mis_builder: analytic_distribution_search removed in 18
  mis_builder/README.rst
  mis_builder/__manifest__.py
  mis_builder/migrations/18.0.1.3.0/post-migration.py
Labels: approved, ready to merge, bot is merging ⏳

#731 [18.0][FWD] mis_builder: Forward updates from 16.0
  mis_builder/models/mis_report_instance.py
  mis_builder/views/mis_report_instance.xml
Labels: approved, bot is merging ⏳
